### ISSUE TITLE
react-woodworm.js.org

### ISSUE THREAD

**Issue by MattIPv4** [robinweser/alveron#12]
# JS.ORG CLEANUP
Hello, it seems a `js.org` subdomain that was requested to target this repository (or another on this user/organisation) no longer works.
The subdomain requested was `react-woodworm.js.org` and had the target of `rofrischmann.github.io/react-woodworm`.
To keep the `js.org` subdomain you should add a page with [reasonable content](https://github.com/js-org/js.org/wiki/No-Content) within a month so the subdomain doesn't resolve to a 404 any longer.
Otherwise the requested subdomain will be removed from JS.ORGs zonefile and the list of active subdomains.

**If you are wanting to keep the `js.org` subdomain and have added [reasonable content](https://github.com/js-org/js.org/wiki/No-Content), YOU MUST reply to the [main cleanup issue](https://github.com/js-org/js.org/issues/2455) with the response format detailed at the top to keep the requested subdomain.**

**Comment by robinweser** [comment]
Oh thanks for notifying me, forgot to remove that!

**Comment by MattIPv4** [comment]
@rofrischmann So do you need the domain still or no?

**Comment by robinweser** [comment]
I don’t need it anymore =) as far I understood the umbrella issue, I just leave it alone and in one month it’ll be gone, right?

**Comment by MattIPv4** [comment]
@rofrischmann Yeah that's correct. Thanks :)
