### ISSUE TITLE
Connect helper

### ISSUE THREAD

**Issue by scerelli** [robinweser/alveron#15]
I was wondering if there's any reason for the absence of a connect helper.

Let's say i have stateful component and I want to call an effect that fetches an API on `componentDidMount`. How can i achieve it without hooks? 

because right now i was trying to use Hooks but i get `useAlveron` is not a function because on import it's an object and not a function, so i suppose my react version doesn't support hooks.

`"react": "16.6.3",`

**Comment by robinweser** [comment]
Why did you close that one? Found that hooks require >16.8.0?
I was just about to answer this week :/

**Comment by scerelli** [comment]
i wrote a sort of helper to achieve something like connect but if you want to keep it open i can reopen it. I got no answer so i thought you were no interested in it.
